version: '3'

services:
  mysql_db:
    container_name: trace_mysql
    image: "mysql:latest"
    restart: always
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=password"
    volumes:
        - "/root/data/mysql:/var/lib/mysql"
  myadmin:
    container_name: trace_myadmin
    image: "phpmyadmin/phpmyadmin:latest"
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
    links:
      - mysql_db
    depends_on:
      - mysql_db
    ports:
      - "8080:80"
  elastic:
     container_name: trace_elastic
     build: infra/elastic/docker
     restart: always
     ports:
          - "9200:9200"
     environment:
          - xpack.security.enabled=false
     volumes:
          - "./infra/elastic/config:/usr/share/elasticsearch/config"
          - "./infra/elastic/docker:/data/elastic"
          - "./infra/elastic/data:/usr/share/elasticsearch/data"