version: '3'

services:
  mysql_db:
    container_name: trace_mysql
    image: "mysql:latest"
    restart: always
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=password"
    volumes:
        - "/root/data/mysql:/var/lib/mysql"
  mongodb:
    container_name: trace_mongo
    build: infra/mongo/
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - "./mongo/:/starter/"
        - "/root/data/mongo:/data/db"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
  elastic:
     container_name: trace_elastic
     build: infra/elastic/
     restart: always
     ports:
          - "9200:9200"
     environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - vm.max_map_count=262144
          - xpack.security.enabled=false
     volumes:
          - "/root/data/escfg:/usr/share/elasticsearch/config"
          - "./infra/elastic:/data/elastic"
          - "/root/data/elastic:/usr/share/elasticsearch/data"